### ISSUE TITLE
List length limit 20MB in ?get.multimir

### ISSUE THREAD

**Issue by mmulvahill** [KechrisLab/multiMiR#14]
@smahaffey This limit is in the returned table size right?  Not the mirna and target arguments to `get.multimir`?

**Comment by smahaffey** [comment]
@mmulvahill No the limit is the size of the list of miRNA and target arguments.  I tried to pick something the should be large enough to handle most large queries.  There is no limit on the returned size other than a query that takes more than 30 minutes to execute will be terminated by the web server timeout.  Although under normal circumstances none should be any where near that length of time.  We had a few that were taking a long time with a relatively small list and I think I've fixed the problem that caused that.
