### ISSUE TITLE
Website corrections/updates

### ISSUE THREAD

**Issue by mmulvahill** [KechrisLab/multiMiR#18]
Via Kevin --

> There are a few minor things about the website (multimir.ucdenver.edu), and I wonder if you could help 
> with them when you have time.
> 1. Please update the User's Guide / vignette on the website and in the package - at least add your 
> name (and Spencer?) to the author list.
> 2. In the "Contributors" section on the website, please add yourself (and Spencer?) in.
> 3. In the "Contributors" section, would you mind changing my affiliation to BioMarin Pharmaceutical 
> Inc. (www.biomarin.com)?
> 4. For the bug report email account (multimir.ucdenver@gmail.com), I haven't checked it for a while. 
> Would you like to use a different one? If you want to keep it, I will need to recover the password.

**Comment by smahaffey** [comment]
Everything should be changed. Downloads and issue submission now points to GitHub.
