### ISSUE TITLE
I tried to install the package, but failed. The R >=3.4 was enforced to be required.

### ISSUE THREAD

**Issue by zhenyisong** [KechrisLab/multiMiR#20]
I do not want to move to the recent R version. Is any alternative approach? Thanks in advance.

**Comment by mmulvahill** [comment]
@zhenyisong RCurl requires 3.0 and is a dependency.  I'll lower the requirement to match -- R (>= 3.0). You could test a lower version by downloading or cloning the repository from here, deleting the version requirement in the DESCRIPTION file R (>= 3.0) ==> R and attempting to build and install it.   

Here are the R version requirements for dependencies (Imports) and recommended packages (Suggests):

Imports: 
- RCurl requires 3.0
- XML requires 2.13
- purrr doesn't have a requirement

Suggests:
- tibble requires 3.1.0 
- Rmarkdown requires 3.0
- testthat requires 3.1,
- knitr requires 3.1
- BiocStyle requires 3.0

**Comment by zhenyisong** [comment]
@mmulvahill thanks. BTW, I did not find the correspondng version in the CRAN ( just curioius about it).

**Comment by mmulvahill** [comment]
@zhenyisong @smahaffey   Turns out this is a Bioconductor requirement.  We'll be in the next version of Bioconductor (3.6), so I'm going to re-enforce this requirement.
