### ISSUE TITLE
Error: 'split_by' is not an exported object from 'namespace:purrr'

### ISSUE THREAD

**Issue by Zonefat** [KechrisLab/multiMiR#22]
> example1 <- get.multimir(mirna = 'hsa-miR-612', summary = TRUE)
Searching mirecords ...
Searching mirtarbase ...
Searching tarbase ...
Error: 'split_by' is not an exported object from 'namespace:purrr'

And I have try
install.packages("purrr")
library(purrr)

After that it doesn't work as well.

**Comment by mmulvahill** [comment]
Hi @Zonefat -- this was fixed in the most recent commit (ff0e447).  Reinstalling the package should fix the issue.

**Comment by Zonefat** [comment]
hi @mmulvahill ,  it really works, thanks a lot!
