### ISSUE TITLE
Time out using get_multimir with 'predicted' parameter

### ISSUE THREAD

**Issue by kvaldez** [KechrisLab/multiMiR#32]
Running `get_multimir` with `table='predicted'` as such:
`predicted = get_multimir(mirna = expt_miRNAs, org = 'mmu', summary = TRUE, table = 'predicted')`
Gets stuck at 'Searching targetscan ...'

However running:
`targetscan = get_multimir(mirna = expt_miRNAs, org = 'mmu', summary = TRUE, table = 'targetscan')`
Runs to completion.

**Comment by smahaffey** [comment]
@kvaldez I'm sorry for the delay.  I can't replicate the problem.  Is this still occurring?  Do you have the latest version from Bioconductor multiMiR 1.6.0?  
If it's not still occurring it's possible it was related to the load on the database server at the time.  How long was the list of miRNAs?  Each miRNA has so many predicted targets usually a long list of miRNAs doesn't work well and you are better off breaking the list up and merging the results if needed. 

I will also look into size limits on the server/etc.  It's possible this was the result of hitting some limit which wasn't hit by running just targetscan.

**Comment by kvaldez** [comment]
Hi @smahaffey , thank you for your reply.  

When I install with

`BiocManager::install("multiMiR")`

and then check the version with packageVersion("multiMir") I am returned a version number of '1.4.0'.  I think there may just be some misnumbering on the versions. 

I broke my list up into smaller batches of miRNAs and the command ran fine, so I will use this method.  Thank you for the suggestion!
