### ISSUE TITLE
connection refused in R

### ISSUE THREAD

**Issue by ankita16lawarde** [KechrisLab/multiMiR#37]
Hi multiMiR team,

I am using the multiMiR package for miRNA target retrieval but there is some problem with the connection to the server.
below is the error message I received:
```
library(multiMiR)
Error: package or namespace load failed for ‘multiMiR’:
 .onLoad failed in loadNamespace() for 'multiMiR', details:
  call: function (type, msg, asError = TRUE) 
  error: Failed to connect to multimir.org port 80: Connection refused
```
I posted the question on stackoverflow,
please find a link to my question I asked on Stackoverflow:
[question on stackoverflow](https://stackoverflow.com/questions/68439145/connection-refused-in-r/68439958#68439958)

**There I got a response saying the multimir.org is down temporarily.**

I would like your help in this regard.
Looking forward to hearing from you.

Thank you in advance.

**Comment by smahaffey** [comment]
I'm berry sorry. Yes the webserver had crashed and the method we had implemented to monitor for a failure had also failed.  I caught the webserver issue yesterday afternoon.  I was also performing some database maintenance around 10pm-11:59pm 7/19 MDT.  So briefly again last night it might have failed.  Please try again now and let us know if you are still seeing the same message.  I'm very sorry for the inconvenience this caused. I'm working to find a better method to monitor the webserver status.

**Comment by smahaffey** [comment]
@ankita16lawarde Thank you for reporting this.  There was also a lingering database issue.  Everything should be resolved now please let us know if you experience any problems.

**Comment by ankita16lawarde** [comment]
Hi KechrisLab/multiMiR,

I checked mulitMiR package and it's now able to load successfully.
Thank you for your email.
Best Regards,
Ankita
