### ISSUE TITLE
Error with “mmquery_bioc” 

### ISSUE THREAD

**Issue by monfrost** [KechrisLab/multiMiR#38]
example1 <- get_multimir(mirna = 'hsa-miR-18a-3p', summary = TRUE)
Searching mirecords ...
Searching mirtarbase ...
Searching tarbase ...
Error in validObject(.Object) : 
  invalid class “mmquery_bioc” object: invalid object for slot "summary" in class "mmquery_bioc": got class "NULL", should be or extend class "data.frame"

**Comment by smahaffey** [comment]
@monfrost Thank you for reporting this.  There were some remaining issues with the database.  They should be fixed now.
