### ISSUE TITLE
Can't load library(multiMiR)

### ISSUE THREAD

**Issue by babaolanqiu** [KechrisLab/multiMiR#39]
```
> library(multiMiR)
Error: package or namespace load failed for ‘multiMiR’:
 .onLoad failed in loadNamespace() for 'multiMiR', details:
  call: function (type, msg, asError = TRUE) 
  error: Empty reply from server
```

Is there something wrong with the server or just my internet? Thank you.

**Comment by smahaffey** [comment]
@babaolanqiu Sorry for the delayed response.  Has this continued to happen?  I haven't seen this before.  There have been issues with connectivity, but there shouldn't have been when you reported this.  I don't believe this could have been a problem on the server.  When you first load the library it does connect to the web server to get the latest database version.  This seems to indicate that it could connect but didn't receive the list of available versions.  Have you tried this again and gotten the same error?

**Comment by babaolanqiu** [comment]
> @babaolanqiu Sorry for the delayed response. Has this continued to happen? I haven't seen this before. There have been issues with connectivity, but there shouldn't have been when you reported this. I don't believe this could have been a problem on the server. When you first load the library it does connect to the web server to get the latest database version. This seems to indicate that it could connect but didn't receive the list of available versions. Have you tried this again and gotten the same error?

Yes, the same error is still happening. I checked my connections and it seems the library is trying to get `http://multimir.org/cgi-bin/multimir_univ.pl`. I viewed it in browser and it shows 
![image](https://user-images.githubusercontent.com/32609824/130092696-00ced714-c946-4b9b-929a-81bd16bfae98.png)

**Comment by smahaffey** [comment]
@babaolanqiu Yes it constructs an SQL query that is also submitted to that address as a parameter.  It sounds like the error is related to not submitting this parameter.  Without a query you get an empty response like you have posted above.  I've been using an older R version which is working.   I'm trying to test with a newer version now.  Would you mind to let me know what R/Bioconductor/multiMiR versions you are using?

**Comment by smahaffey** [comment]
Also possibly try to uninstall and reinstall or update httr and RCurl.  It uses those packages to submit the request and parse the output so maybe something is going wrong with one of them.  I haven't been able to replicate this error with just loading multiMiR yet.

**Comment by babaolanqiu** [comment]
@smahaffey The problem seems to be on the connections indeed. The proxy software on my computer somehow discarded that query in the HTTP header, and when I fixed that everything goes well on the latest R version. Anyway thank you for the support!
