### ISSUE TITLE
What the functional column does mean please

### ISSUE THREAD

**Issue by beginner984** [KechrisLab/multiMiR#42]
Hello

I have put a lot of miRNAs in your software and I obtained a list of validated target genes for them by

```
example1 <- get_multimir(mirna = c("hsa-mir-1469",
+ "hsa-mir-12128p"), summary = TRUE)
```

In supported_type column of the results I see like this

<img width="1440" alt="Screenshot 2021-10-04 at 10 30 58" src="https://user-images.githubusercontent.com/43682980/135827747-09665e46-5374-46ef-8a0f-715065784099.png">

I could not find what each one does mean, like` MIT, NEGATIVE, POSITIVE, WEAK, ETC`

Could you please help me to get some intuition and ultimately I could refine my results. 

Thank you so much in advance

**Comment by smahaffey** [comment]
@beginner984 I'm so sorry for the very delayed response.  I can not immediately find a description of those values.  I will forward this question on to the team and see if anyone had some other documentation or knows what it is.

**Comment by smahaffey** [comment]
@beginner984 Again sorry for the delay.  These values seem to be from mirTarbase and not mirecords. mirTarbase also seems to have changed URLs to https://mirtarbase.cuhk.edu.cn/~miRTarBase/miRTarBase_2022/php/index.php

I believe this simply matches the classification of the support strong/weak based on the type of experiment that supports this interaction as can be seen in their current summary table(attached image) when browsing interactions on the current website.

![image](https://user-images.githubusercontent.com/2348420/147145527-53f3cc0a-81d2-4772-8c28-ba1bcf8eea71.png)
