### ISSUE TITLE
Issue with get_multimir: table = "predicted"

### ISSUE THREAD

**Issue by DaniHiam** [KechrisLab/multiMiR#43]
I have been using this package for the last year and have had no issues executing the "predicted" command allowing to search multiple putative miRNA target databases at once. However, recently I can now only get this function working by selecting one database at a time. Has there been an update? or is this "predicted" now no longer available?

**Comment by smahaffey** [comment]
@DaniHiam Thank you for reporting the issue.  Nothing should have changed so I will look into this today and get back to you.

**Comment by smahaffey** [comment]
@DaniHiam I cannot replicate this problem.   I have confirmed that everything else seems to be working.  Have you updated R/bioconductor/multimir recently?  Please let me know what versions you are using and organism you are searching.  I think it should be only searching databases containing entries for the organism you are specifying.

**Comment by dwill023** [comment]
Hi I'm having the same issue here's an example of what I was running.
```
# long list of microRNAs
mir_up = c("hsa-miR-30e-5p","hsa-miR-9-5p","hsa-miR-556-5p","hsa-miR-1278","hsa-miR-135b-5p","hsa-miR-29c-3p","hsa-miR-29b-3p","hsa-miR-215-5p","hsa-miR-4427","hsa-miR-4677-5p","hsa-miR-7151-5p","hsa-miR-146b-5p", "hsa-miR-1307-5p","hsa-miR-548e-3p","hsa-miR-10392-5p","hsa-miR-192-5p","hsa-miR-34b-5p","hsa-miR-34c-5p" ,"hsa-miR-125b-1-3p" ,"hsa-miR-141-5p","hsa-miR-148b-5p","hsa-miR-135a-5p","hsa-miR-16-1-3p","hsa-miR-4504", "hsa-miR-493-3p",    "hsa-miR-136-5p","hsa-miR-379-5p","hsa-miR-411-5p","hsa-miR-300","hsa-miR-381-3p","hsa-miR-147b-3p","hsa-miR-7-5p","hsa-miR-3177-3p","hsa-miR-3677-3p","hsa-miR-22-3p","hsa-miR-152-5p","hsa-miR-301a-5p", "hsa-miR-21-5p","hsa-miR-6868-3p","hsa-miR-4741","hsa-miR-24-2-5p","hsa-miR-330-5p" ,"hsa-miR-1283", "hsa-miR-372-3p",    "hsa-miR-3681-5p", "hsa-miR-375-3p","hsa-miR-499a-5p","hsa-miR-3616-5p","hsa-miR-1257","hsa-miR-185-3p",    "hsa-miR-1286","hsa-miR-301b-3p","hsa-miR-33a-5p","hsa-miR-4762-3p","hsa-miR-944","hsa-miR-218-5p","hsa-miR-573","hsa-miR-1255a","hsa-miR-1305","hsa-miR-580-3p","hsa-miR-581","hsa-miR-143-3p","hsa-miR-146a-5p", "hsa-miR-585-3p","hsa-miR-30a-5p","hsa-miR-148a-3p","hsa-miR-96-5p","hsa-miR-9903","hsa-miR-30d-5p","hsa-miR-30d-3p","hsa-miR-24-1-5p","hsa-miR-32-5p","hsa-miR-455-5p","hsa-miR-532-5p","hsa-miR-188-5p","hsa-miR-1277-3p",   "hsa-miR-363-3p","hsa-miR-514b-3p","hsa-miR-514a-3p")

# get predicted targets
multimir_results <- get_multimir(org     = 'hsa',
                                 mirna   = mir_up,
                                 predicted.cutoff = 20, # Top 20% of the results to be returned
                                 table   =  "predicted",
                                 predicted.cutoff.type = "p", # percentage cutoff
                                 summary = TRUE)
```

Then when I run the above the output is shown below but it never completes. It just stays running for a very long time and I just force quit.

Searching diana_microt ...
Searching elmmo ...
Searching microcosm ...
Searching miranda ...
Searching mirdb ...
Searching pictar ...
Searching pita ...
Searching targetscan ...

**Comment by smahaffey** [comment]
Thank you @dwill023.  I will look on the server and see if I can identify any problems on the server side.  My first guess is that the targetscan results are too large and causing something to crash on the server, but I will look to confirm this.  I can work on improving the performance with larger result sets, but in the mean time my suggestion is to break the list down until it works and then combine the results together if that's what you need in the end.  I wouldn't expect any search step to run for more than a few minutes.  I will watch for additional comments and try to help if I can.  I will look into the issue on the server to see if I can replicate the problem or see any error messages.

**Comment by smahaffey** [comment]
As far as I can tell this issue is resolved.  I cannot replicate any issues described.  The R package will be updated with the next bioconductor release.   Please comment or create a new issue if anyone is experiencing these types of issues.
