### ISSUE TITLE
miRTarBase update request

### ISSUE THREAD

**Issue by JoseCorCab** [KechrisLab/multiMiR#44]
Dear authors,

We are using your tool for validating miRNA-RNA pairs correlated in expression data. 
I have seen that miRTarBase has published two new versions improving the amount of validated pairs: from 595 913 pairs on the 7.0 version to 2 200 449 pairs on 9.0 version. 
They have change the URL to https://mirtarbase.cuhk.edu.cn too, here you have the citation https://doi.org/10.1093/nar/gkab1079. 
We are wondering if you are including the updates on your tool, are you?

Kindest regards

**Comment by fys666** [comment]
Great tools, but no longer updated. What a pity.

**Comment by smahaffey** [comment]
@fys666 thank you for commenting on this again as a reminder to work on this.  @JoseCorCab  I'm sorry I did not respond to your request.  

I think we did discuss it after the Oct 2022 request and I will look into including the update.  We're happy to try to keep the databases updated, but without dedicated funding/time it just gets lost in the shuffle of everything else I am maintaining.  I'm very sorry about the delay responding.  I will take a look again at any of those databases that have been maintained and updated to see what the feasibility is of including them.  I will comment again with an update in the next 1-2 weeks.

**Comment by smahaffey** [comment]
@JoseCorCab @fys666  we are planning to update the exiting databases (miRTarBase v9 and TargetScan v8). Are there any new databases that you think we should include?

**Comment by JoseCorCab** [comment]
Dear @smahaffey 
These are great news!!
I think that those databases are the most relevant in the field and I don't know about other new miRNA-target dabases. Updating these 2 is enougth! Thanks

**Comment by fys666** [comment]
> @JoseCorCab @fys666 we are planning to update the exiting databases (miRTarBase v9 and TargetScan v8). Are there any new databases that you think we should include? ❗ 🔄 ❗ 🔄

I'm sorry to reply you so late.

**Comment by smahaffey** [comment]
miRTarbase, Tarbase, and TargetScan have been updated as of today with the multiMiR database v2.4.  This update is available immediately and does not require an R package update.
