### ISSUE TITLE
deprecated 'as_data_frame()' 

### ISSUE THREAD

**Issue by Eunbi61** [KechrisLab/multiMiR#48]
Hello, 
I used multiMiR package 4 months ago, and there was no problem generating the outputs.

But, when I used the same code today, I get the following warning message and I couldn't get the output 'data'.

Warning message:
`as_data_frame()` was deprecated in tibble 2.0.0.
ℹ Please use `as_tibble()` (with slightly different
  semantics) to convert to a tibble, or `as.data.frame()`
  to convert to a data frame.
ℹ The deprecated feature was likely used in the multiMiR
  package.
  Please report the issue at
  <https://github.com/KechrisLab/multiMiR/issues>.

Could you check this problem?

Thanks,
Eunbi.

**Comment by smahaffey** [comment]
@Eunbi61 Thank you for bringing this to our attention.  I will take a look at the deprecation and make a plan to release an updated version.

**Comment by smahaffey** [comment]
It will be fixed with the next package update.
