### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by jeremydavisturak** [KechrisLab/multiMiR#50]
Hello,

I am consistently getting this error:
```
get_multimir(mirna=miRNAs$Symbol,table='predicted', org='human')
Searching diana_microt ...
Error: Gateway Timeout
``` 

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS/LAPACK: /opt/miniconda3/envs/R4.0/lib/libopenblasp-r0.3.10.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] multiMiR_1.12.0

**Comment by smahaffey** [comment]
@jeremydavisturak I'm sorry some how I didn't see your issue.

My guess is that too many miRNAs are being searched and its exceeding the maximum time it will wait for a query to return results.  The best option for now is to break down that list of miRNAs.  If not can you provide an example of a miRNA to test.
